spring:
  profiles: default

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:5555}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:5555}/eureka/

hello: there

---

spring:
  profiles: mikey

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:5556}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:5556}/eureka/

hello: there
